name = "lux-scepter"
compatibility_date = "2025-11-26"
pages_build_output_dir = "public"

[vars]
JWT_SECRET = "change-this-to-a-random-32-char-string"

[[r2_buckets]]
binding = "R2"
bucket_name = "lux-scepter-media"

[[d1_databases]]
binding = "DB"
database_name = "luxdb"
database_id = "" # â† will be filled automatically

[triggers]
crons = []

[[routes]]
pattern = "yoursite.com/*"
custom_domain = true
