name = "lux-scepter"
compatibility_date = "2025-11-26"
pages_build_output_dir = "public"

[vars]
JWT_SECRET = "f9D4k8X1vB7qR3mZ2sL0pT6wN5jH8yCk"

[[r2_buckets]]
binding = "R2"
bucket_name = "lux-scepter-media"

[[d1_databases]]
binding = "DB"
database_name = "luxdb"
database_id = "" # ‚Üê will be filled automatically
